import type { Article } from "@/data/articles";

// Image Imports from assets
import featuredImage from "@/assets/vintage-repurposed-halloween-decor-featured.jpg";
import catGhostLanternImg from "@/assets/haunted-hill-farm-cat-ghost-pillar-lantern.jpg";
import flockedPumpkinImg from "@/assets/haunted-hill-farm-flocked-pumpkin-stack.jpg";
import hauntedHouseFlatbackImg from "@/assets/haunted-hill-farm-led-haunted-house-flatback.jpg";
import pumpkinFlatbackImg from "@/assets/haunted-hill-farm-led-pumpkin-flatback.jpg";
import spookyJackOSetImg from "@/assets/haunted-hill-farm-spooky-jack-o-set.jpg";
import ghostFamilyImg from "@/assets/haunted-hill-farm-ghost-family.jpg";
import witchPotionImg from "@/assets/haunted-hill-farm-witch-pouring-potion.jpg";
import ghostSignImg from "@/assets/haunted-hill-farm-led-ghost-happy-halloween-sign.jpg";
import polkaDotPumpkinImg from "@/assets/haunted-hill-farm-polka-dot-pumpkin-stack.jpg";
import metalScarecrowImg from "@/assets/haunted-hill-farm-led-metal-scarecrow.jpg";
import candleBlowMoldImg from "@/assets/haunted-hill-farm-led-candle-blow-mold.jpg";
import ledSkeletonImg from "@/assets/haunted-hill-farm-led-skeleton-decoration.jpg";
import summerweenPumpkinImg from "@/assets/haunted-hill-farm-summerween-pumpkin-stack.jpg";
import creepyDollImg from "@/assets/haunted-hill-farm-creepy-doll.jpg";
import hauntedHouseSetImg from "@/assets/haunted-hill-farm-led-haunted-house-set.jpg";
import bearRockingHorseImg from "@/assets/haunted-hill-farm-bear-rocking-horse.jpg";

export const article: Article = {
  slug: "vintage-repurposed-halloween-decor",
  title: "16 Vintage Halloween Decor Ideas Using Repurposed Antiques and Found Objects",
  excerpt:
    "Breathe haunting new life into thrifted treasures. 16 creative vintage Halloween decor ideas pairing repurposed ladders, crates, and antique window frames with illuminated harvest props.",
  answer:
    "Creating an authentic repurposed vintage Halloween display means pairing weathered rustic architectural salvage (wooden ladders, apple crates, chippy window sashes) with illuminated focal pieces like blow mold candles, metal silhouettes, and jack-o'-lantern lanterns.",
  category: "holidays",
  event: "Halloween",
  season: "Fall",
  tags: [
    "Halloween Decorations",
    "Outdoor Decor",
    "Porch Decor",
    "Halloween",
    "Home & Garden",
    "vintage",
    "repurposed-antiques",
    "found-objects",
    "farmhouse-halloween",
  ],
  author: "sarah-linden",
  published: "2026-09-02",
  updated: "2026-09-02",
  views: 35400,
  readingMinutes: 12,
  image: featuredImage,
  imageWidth: 1266,
  imageHeight: 707,
  featured: false,

  // Extended SEO & Content Metadata
  metaTitle: "16 Repurposed Vintage Halloween Decor Ideas (Found Objects) | Celebration Stuff",
  metaDescription:
    "Transform thrift store finds into spooky front porch magic. 16 vintage Halloween decor ideas using repurposed wooden ladders, crates, old books, and glowing lanterns.",
  canonicalUrl: "https://celebrationstuff.com/article/vintage-repurposed-halloween-decor",
  featuredImageAlt:
    "Rustic front porch with repurposed wooden ladder, vintage apple crates, and glowing Halloween lanterns",
  primaryKeyword: "vintage repurposed halloween decor antiques found objects",
  secondaryKeywords: [
    "repurposed vintage halloween decorations",
    "antique found objects halloween porch decor",
    "upcycled rustic halloween decor ideas",
    "thrift store vintage halloween yard displays",
  ],
  focusTopic: "Architectural Salvage, Upcycled Antiques & Found-Object Halloween Staging",
  recipient: ["homeowners", "diy-enthusiasts", "thrifters"],
  occasion: ["halloween", "home-makeover"],
  holiday: ["halloween"],
  giftStyle: ["outdoor-decor", "vintage", "rustic", "upcycled"],

  sections: [
    {
      id: "introduction",
      heading: "16 Vintage Halloween Decor Ideas Using Repurposed Antiques and Found Objects",
      body: [
        "There's something deeply satisfying about repurposing old things.",
        "An antique ladder becomes a vertical plant and lantern stand. A vintage apple crate becomes a rustic porch centerpiece. Old books, mason jars, and worn-out window frames find new life as haunting autumn decorations. It's sustainable, it's creative, and it adds a layer of authenticity that store-bought plastic decor simply can't match. To see how these found-object displays compare to giant neighborhood centerpieces, explore our master guide on [17 outdoor Halloween decorations that actually impress the neighbors](/article/outdoor-halloween-decorations-impress-neighbors).",
        "Even the most beautiful repurposed display benefits from a few quality pieces that do the heavy lifting. A vintage blow mold candle here. A glowing pillar lantern there. These pieces anchor your found-object display with warm illumination and weather-resistant durability. For more household upcycling ideas, explore our guide on [14 Halloween yard ideas using items you already have at home](/article/diy-halloween-yard-ideas-home-items).",
        "We've rounded up 16 vintage Halloween decor ideas using repurposed antiques and found objects — paired with curated props to create a display that looks curated, collected, and completely authentic. For more straw-bale staging inspiration, check out our [17 Halloween porch ideas combining pumpkins and hay bales](/article/pumpkin-hay-bale-porch-ideas).",
      ],
    },
    {
      id: "quick-picks",
      heading: "Quick Picks — Best Repurposed Antique Decor Ideas",
      body: [
        "| Idea | Product | Repurposed Item |\n|---|---|---|\n| **The Vintage Ladder Display** | Haunted Hill Farm Cat & Ghost Lantern | Old wooden ladder |\n| **The Crate Scene** | Haunted Hill Farm Flocked Pumpkin Stack | Rustic wooden crate |\n| **The Window Frame** | Haunted Hill Farm Haunted House Flatback | Old window frame |\n| **The Book Display** | Haunted Hill Farm LED Pumpkin Flatback | Vintage hardcover books |\n| **The Mason Jar Glow** | Haunted Hill Farm Spooky Jack O Set | Old mason jars |",
      ],
    },
    {
      id: "haunted-hill-farm-cat-ghost-lantern",
      heading: "1. The Ladder Display — Haunted Hill Farm Cat & Ghost Pillar Lantern + Old Ladder",
      productId: "haunted-hill-farm-cat-ghost-lantern",
      body: [
        "That old wooden ladder in your garage or attic? It's Halloween gold.",
        "Lean it securely against your porch wall or railing. Place the Cat & Ghost Pillar Lantern on one rung and a few heirloom pumpkins or gourds on others. The contrast between weathered barn wood and the elegant black silhouette lantern creates an instant designer moment. For more entryway hospitality styling, see [11 Halloween porch decorations that welcome guests with style](/article/stylish-halloween-porch-decorations).",
        "**What you need:** Old wooden ladder + Cat & Ghost Pillar Lantern.",
        "[Check the current price on Amazon →](https://amzn.to/4xwgUKk)",
      ],
    },
    {
      id: "haunted-hill-farm-flocked-pumpkin",
      heading: "2. The Crate Scene — Haunted Hill Farm Flocked Pumpkin Stack + Wooden Crate",
      productId: "haunted-hill-farm-flocked-pumpkin",
      body: [
        "An old wooden apple or milk crate is the ultimate rustic base for a vintage display.",
        "Place the crate on its side on your porch. Set the Flocked Pumpkin Stack on top, and tuck dried hydrangeas or amber glass bottles into the cubby underneath. It's a farmhouse-inspired vignette that feels gathered from a countryside antique barn. For more authentic vintage items, browse [27 vintage Halloween decor that actually looks authentic](/article/authentic-vintage-halloween-decor).",
        "**What you need:** Vintage wooden crate + Flocked Pumpkin Stack.",
        "[Check the current price on Amazon →](https://amzn.to/4gCB4wh)",
      ],
    },
    {
      id: "haunted-hill-farm-haunted-house-flatback",
      heading: "3. The Window Frame — Haunted Hill Farm Haunted House Flatback + Old Frame",
      productId: "haunted-hill-farm-haunted-house-flatback",
      body: [
        "An antique six-pane window sash becomes a haunted architectural shadowbox.",
        "Hang or lean the window frame against your siding, and center the LED Haunted House Flatback behind it. The warm amber light spilling from the windows makes it look like a spooky Victorian painting brought to three-dimensional life. For small entryways, read [12 Halloween yard decorations ideas for small spaces](/article/small-space-halloween-yard-ideas).",
        "**What you need:** Old window frame + LED Haunted House Flatback.",
        "[Check the current price on Amazon →](https://amzn.to/4cP1UPa)",
      ],
    },
    {
      id: "haunted-hill-farm-pumpkin-flatback",
      heading: "4. The Book Display — Haunted Hill Farm LED Pumpkin Flatback + Vintage Books",
      productId: "haunted-hill-farm-pumpkin-flatback",
      body: [
        "Stack weathered, clothbound vintage hardcover books on a porch side table.",
        "Rest the glowing LED Pumpkin Flatback right on top of the book stack. The combination of gold-embossed spines and warm LED candlelight is pure autumnal literary nostalgia. If you are decorating on a budget, explore our guide to [outdoor Halloween decor on a budget](/article/outdoor-halloween-decor-budget-ideas).",
        "**What you need:** Old hardcover books + LED Pumpkin Flatback.",
        "[Check the current price on Amazon →](https://amzn.to/4xnZmzQ)",
      ],
    },
    {
      id: "haunted-hill-farm-spooky-jack-o-set",
      heading: "5. The Mason Jar Glow — Haunted Hill Farm Spooky Jack O Set + Mason Jars",
      productId: "haunted-hill-farm-spooky-jack-o-set",
      body: [
        "Fill vintage zinc-lidded Ball mason jars with battery-operated amber fairy lights.",
        "Alternate the glowing jars along your porch steps alongside the Spooky Jack O Set lanterns. The blend of farmhouse glass and carved pumpkin grins creates a warm, enchanting walkway for trick-or-treaters. For more evening lighting ideas, read [16 Halloween yard decorations that light up the night](/article/halloween-yard-decorations-light-up-night).",
        "**What you need:** Old mason jars + fairy lights + Spooky Jack O Set.",
        "[Check the current price on Amazon →](https://amzn.to/4y2E8Y4)",
      ],
    },
    {
      id: "haunted-hill-farm-ghost-family",
      heading: "6. The Antique Chair — Haunted Hill Farm Ghost Family + Old Chair",
      productId: "haunted-hill-farm-ghost-family",
      body: [
        "A weather-beaten wooden rocking chair becomes a haunting throne for spectral guests.",
        "Stage the Ghost Family around and behind the rocking chair — it looks as though an ethereal family is gathered for an evening ghost story. Add a flickering candle blow mold nearby for atmospheric shadow play. For more family-friendly setups, see [13 Halloween yard ideas perfect for families with young kids](/article/family-friendly-halloween-yard-ideas).",
        "**What you need:** Old wooden chair + Ghost Family Animatronic.",
        "[Check the current price on Amazon →](https://amzn.to/4i4mzCw)",
      ],
    },
    {
      id: "haunted-hill-farm-witch-potion",
      heading: "7. The Vintage Washstand — Haunted Hill Farm Witch Pouring Potion + Old Table",
      productId: "haunted-hill-farm-witch-potion",
      body: [
        "An antique washstand or small console table is the ideal apothecary bench.",
        "Position the Witch Pouring Potion on top alongside antique cobalt apothecary bottles and dried lavender bundles. The animated pouring motion brings the antique furniture to life. For more playful storybook accents, read [15 Halloween porch decorations for people who love whimsy](/article/whimsical-halloween-porch-decorations).",
        "**What you need:** Old washstand or table + Witch Pouring Potion.",
        "[Check the current price on Amazon →](https://amzn.to/4iBZGX4)",
      ],
    },
    {
      id: "haunted-hill-farm-ghost-sign",
      heading: "8. The Old Door — Haunted Hill Farm Ghost Sign + Vintage Door",
      productId: "haunted-hill-farm-ghost-sign",
      body: [
        "Lean a salvaged five-panel wooden door against your porch wall.",
        "Hang the illuminated Ghost Sign right at eye level on the door. The weathered, peeling paint contrasts beautifully with the warm LED border, giving trick-or-treaters the feeling of visiting a vintage carnival or general store.",
        "**What you need:** Old wooden door + LED Ghost Happy Halloween Sign.",
        "[Check the current price on Amazon →](https://amzn.to/4hZl5JC)",
      ],
    },
    {
      id: "haunted-hill-farm-polka-dot-pumpkin",
      heading: "9. The Vintage Crate Stack — Haunted Hill Farm Polka Dot Pumpkin Stack + Crates",
      productId: "haunted-hill-farm-polka-dot-pumpkin",
      body: [
        "Stack staggered vintage crates to create multi-tiered architectural height.",
        "Crest the tallest crate with the Polka Dot Pumpkin Stack. The juxtaposition of rough weathered wood and crisp courtly check patterns feels straight out of an upscale country design catalogue. For more high-end porch tips, explore [13 Halloween porch decorations that look high-end](/article/high-end-halloween-porch-decorations).",
        "**What you need:** Vintage crates + Polka Dot Pumpkin Stack.",
        "[Check the current price on Amazon →](https://amzn.to/3V2VMg6)",
      ],
    },
    {
      id: "haunted-hill-farm-metal-scarecrow",
      heading: "10. The Old Bucket — Haunted Hill Farm Metal Scarecrow + Vintage Bucket",
      productId: "haunted-hill-farm-metal-scarecrow",
      body: [
        "An antique galvanized metal washtub or sap bucket makes the perfect rustic urn.",
        "Anchor the Metal Scarecrow inside the galvanized tub, filling the base with real straw and dried corn stalks. The metal-on-metal texture looks rugged and timeless. For harvest styling, see [19 vintage Halloween decorations for a nostalgic harvest celebration](/article/vintage-harvest-halloween-decorations).",
        "**What you need:** Vintage galvanized bucket + LED Metal Scarecrow.",
        "[Check the current price on Amazon →](https://amzn.to/4zOJic3)",
      ],
    },
    {
      id: "haunted-hill-farm-candle-blow-mold",
      heading: "11. The Vintage Suitcase — Haunted Hill Farm LED Candle + Old Suitcase",
      productId: "haunted-hill-farm-candle-blow-mold",
      body: [
        "Prop open a battered vintage leather or tweed suitcase on your stoop.",
        "Nestle the Warm White LED Candle Blow Mold inside so warm amber light spills outward across the threshold. It looks like an eccentric 1920s ghost traveler just unpacked their belongings. For silent film inspiration, see [13 vintage Halloween decor pieces for a 1920s horror film yard](/article/vintage-horror-film-halloween-yard).",
        "**What you need:** Vintage suitcase + Warm White LED Candle Blow Mold.",
        "[Check the current price on Amazon →](https://amzn.to/4wZhAH2)",
      ],
    },
    {
      id: "haunted-hill-farm-led-skeleton",
      heading: "12. The Old Mirror — Haunted Hill Farm White LED Skeleton + Vintage Mirror",
      productId: "haunted-hill-farm-led-skeleton",
      body: [
        "Lean an ornate antique mirror with a distressed or clouded silver backing against the porch wall.",
        "Position the White LED Skeleton so its illuminated ribs reflect in the glass. The double image creates a spine-tingling illusion of a phantom trapped inside the looking glass. For gothic horror atmosphere, check out [11 vintage Halloween decorations for a creepy old-fashioned vibe](/article/creepy-vintage-halloween-decorations).",
        "**What you need:** Old framed mirror + White LED Skeleton.",
        "[Check the current price on Amazon →](https://amzn.to/4gu19xh)",
      ],
    },
    {
      id: "haunted-hill-farm-summerween-pumpkin",
      heading: "13. The Vintage Cart — Haunted Hill Farm Summerween Pumpkin Stack + Garden Cart",
      productId: "haunted-hill-farm-summerween-pumpkin",
      body: [
        "A weathered Radio Flyer wagon or antique wooden wheelbarrow makes an eye-catching mobile display.",
        "Arrange the Summerween Pumpkin Stack in the cart surrounded by real heirloom green and white Cinderella pumpkins. Roll it beside your front walkway for an instant harvest farmstand display. For more nostalgic ideas, see [15 vintage Halloween decor ideas that bring nostalgia to your front yard](/article/vintage-halloween-yard-decor-ideas).",
        "**What you need:** Vintage garden cart + Summerween Pumpkin Stack.",
        "[Check the current price on Amazon →](https://amzn.to/4i4l8nA)",
      ],
    },
    {
      id: "haunted-hill-farm-creepy-doll",
      heading: "14. The Old Birdcage — Haunted Hill Farm Creepy Doll + Vintage Birdcage",
      productId: "haunted-hill-farm-creepy-doll",
      body: [
        "Suspend an antique wrought-iron or wire birdcage from your porch ceiling hook.",
        "Seat the motorized Creepy Doll inside the cage. When guests approach and she turns her porcelain head with tinkling music box audio, it delivers pure psychological horror straight out of an Edwardian ghost story.",
        "**What you need:** Vintage hanging birdcage + Creepy Doll Animatronic.",
        "[Check the current price on Amazon →](https://amzn.to/4h24WlD)",
      ],
    },
    {
      id: "haunted-hill-farm-haunted-house-set",
      heading: "15. The Vintage Paint Cans — Haunted Hill Farm Haunted House Set + Old Paint Cans",
      productId: "haunted-hill-farm-haunted-house-set",
      body: [
        "Stack weathered vintage metal paint or oil cans as industrial risers.",
        "Perch the 3-piece Haunted House Set on top of the rustic cans along your steps. The unexpected contrast between industrial metal and glowing gothic manor silhouettes creates a truly artistic vignette. For daylight tips, see [19 Halloween porch decor that looks great in daylight](/article/halloween-porch-decor-daylight).",
        "**What you need:** Weathered metal cans + LED Spooky Haunted House Set.",
        "[Check the current price on Amazon →](https://amzn.to/46yvbtS)",
      ],
    },
    {
      id: "haunted-hill-farm-bear-rocking-horse",
      heading: "16. The Old Farm Tools — Haunted Hill Farm Bear on a Horse + Vintage Tools",
      productId: "haunted-hill-farm-bear-rocking-horse",
      body: [
        "Lean an antique wooden-handled rake, pitchfork, or scythe against your porch post.",
        "Set the Bear Riding Rocking Horse right beside the tools. The gentle rocking teddy bear combined with genuine rustic farm implements evokes an abandoned 19th-century homestead. If you need a fast setup, read [12 easy Halloween porch decor ideas you can set up in 30 minutes](/article/quick-easy-halloween-porch-decor).",
        "**What you need:** Antique farm tools + Bear Riding Rocking Horse Animatronic.",
        "[Check the current price on Amazon →](https://amzn.to/4ybKvs7)",
      ],
    },
    {
      id: "quick-repurposed-setup-guide",
      heading: "Quick Repurposed Display Setup Guide",
      body: [
        "| Step | Action | Time |\n|---|---|---|\n| 1 | Gather 2–3 vintage architectural pieces from home or thrift store | 10 minutes |\n| 2 | Select illuminated focal pieces from the list above | 5 minutes |\n| 3 | Arrange salvage into a stable vignette | 10 minutes |\n| 4 | Add warm amber lighting and plug in | 5 minutes |\n| 5 | Step back, evaluate balance, and adjust | 5 minutes |\n\n**Total time:** ~35 minutes",
      ],
    },
    {
      id: "create-repurposed-vintage-display",
      heading: "Create Your Own Vintage Repurposed Display",
      body: [
        "The best vintage displays tell a story. They combine old and new — something with history and patina, paired with durable, modern illuminated craftsmanship.",
        "Start with one or two found objects from around your home, garage, or local flea market. Anchor them with a high-impact piece from this collection. And let your imagination turn your porch into an unforgettable autumn showcase.",
      ],
    },
  ],

  products: [
    {
      id: "haunted-hill-farm-cat-ghost-lantern",
      name: "Haunted Hill Farm 2.7-Ft. Cat & Ghost Pillar Halloween Lantern",
      image: catGhostLanternImg,
      imageAlt: "Haunted Hill Farm 2.7-Ft Cat & Ghost Pillar Lantern",
      price: "$44.99",
      why: "Architectural lantern column with laser-cut silhouettes that pairs seamlessly with vintage wooden ladders and crates.",
      keyDetails: [
        "Laser-cut cat and ghost silhouette panels",
        "Flickering flameless LED candle interior",
        "2.7-foot substantial height fits ladder rungs and steps",
        "Matte weatherproof black resin finish",
      ],
      consider: "Position on ladder rungs for vertical height.",
      amazonUrl: "https://amzn.to/4xwgUKk",
      bestFor: "Repurposed ladder vignettes",
      badge: "Best Ladder Accent",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-flocked-pumpkin",
      name: "Haunted Hill Farm 2.4-Ft. Flocked Pumpkin Stack Halloween Decor",
      image: flockedPumpkinImg,
      imageAlt: "Haunted Hill Farm 2.4-Ft Flocked Pumpkin Stack",
      price: "$44.99",
      why: "Velvety flocked pumpkin stack that brings tactile elegance when displayed on top of rustic apple crates.",
      keyDetails: [
        "Tactile velvety flocked finish",
        "Muted creamy neutral color palette",
        "2.4-foot graduated stacked form",
        "Weatherproof resin construction",
      ],
      consider: "Elevates ordinary wooden fruit crates.",
      amazonUrl: "https://amzn.to/4gCB4wh",
      bestFor: "Rustic crate pedestals",
      badge: "Best Crate Topper",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-haunted-house-flatback",
      name: "Haunted Hill Farm 2-Ft. LED Haunted House Flatback Halloween Decoration",
      image: hauntedHouseFlatbackImg,
      imageAlt: "Haunted Hill Farm 2-Ft LED Haunted House Flatback",
      price: "$36.99",
      why: "Victorian facade with glowing amber windows that looks like a haunted shadowbox behind antique window sashes.",
      keyDetails: [
        "Victorian gothic architectural facade",
        "Glowing amber LED window panes",
        "Flatback design hangs or leans flush against frames",
        "Durable outdoor resin",
      ],
      consider: "Center inside old window frames.",
      amazonUrl: "https://amzn.to/4cP1UPa",
      bestFor: "Window sash shadowboxes",
      badge: "Best Frame Art",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-pumpkin-flatback",
      name: "Haunted Hill Farm 1.8-Ft. LED Pumpkin Flatback Halloween Decoration",
      image: pumpkinFlatbackImg,
      imageAlt: "Haunted Hill Farm 1.8-Ft LED Pumpkin Flatback",
      price: "$32.99",
      why: "Smiling glowing jack-o'-lantern with flat base that perches perfectly on stacks of vintage hardcover books.",
      keyDetails: [
        "Warm internal golden LED glow",
        "Cheerful carved smiling pumpkin expression",
        "Flatback design rests securely on book stacks",
        "Weatherproof all-season resin",
      ],
      consider: "Classic comforting Halloween motif.",
      amazonUrl: "https://amzn.to/4xnZmzQ",
      bestFor: "Vintage book stacks",
      badge: "Best Book Topper",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-spooky-jack-o-set",
      name: "Haunted Hill Farm Warm White LED Spooky Jack O Set Lantern 3 pc.",
      image: spookyJackOSetImg,
      imageAlt: "Haunted Hill Farm Warm White LED Spooky Jack O Set Lantern 3 pc",
      price: "$99.99",
      why: "Three graduated pumpkins with warm candle-flicker illumination that harmonize with antique mason jars.",
      keyDetails: [
        "Deeply sculpted carved relief faces",
        "Warm candle-flicker LED illumination",
        "Set of 3 graduated round pumpkin heights",
        "Authentic turn-of-the-century harvest mood",
      ],
      consider: "Step guidance in pure retro style.",
      amazonUrl: "https://amzn.to/4y2E8Y4",
      bestFor: "Mason jar stair vignettes",
      badge: "Best Step Lanterns",
      rating: 4.9,
    },
    {
      id: "haunted-hill-farm-ghost-family",
      name: "Haunted Hill Farm 5.3-Ft. Ghost Family Halloween Animatronic",
      image: ghostFamilyImg,
      imageAlt: "Haunted Hill Farm 5.3-Ft Ghost Family Animatronic",
      price: "$139.99",
      why: "A family trio of gentle specters with synchronized swaying that looks hauntingly seated around antique chairs.",
      keyDetails: [
        "Gentle motorized swaying motion",
        "Soft internal spectral LED face illumination",
        "Tiered family heights up to 5.3 feet",
        "Heartwarming nostalgic character presentation",
      ],
      consider: "Adds genuine ghost story atmosphere to the lawn.",
      amazonUrl: "https://amzn.to/4i4mzCw",
      bestFor: "Antique rocking chair scenes",
      badge: "Best Ghost Family",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-witch-potion",
      name: "Haunted Hill Farm 1.8-Ft. Witch Pouring Potion Tabletop Animatronic",
      image: witchPotionImg,
      imageAlt: "Haunted Hill Farm 1.8-Ft Witch Pouring Potion Animatronic",
      price: "$69.99",
      why: "Animated storybook witch brewing potions that turns salvaged washstands into an antique apothecary counter.",
      keyDetails: [
        "Motorized animated potion pouring action",
        "Glowing green LED cauldron potion",
        "Cackling spellcasting monologue audio",
        "Compact 1.8-foot tabletop scale",
      ],
      consider: "Sets neatly on antique washstands.",
      amazonUrl: "https://amzn.to/4iBZGX4",
      bestFor: "Antique washstand apothecaries",
      badge: "Best Storybook Witch",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-ghost-sign",
      name: "Haunted Hill Farm 2-Ft. LED Ghost Happy Halloween Sign",
      image: ghostSignImg,
      imageAlt: "Haunted Hill Farm 2-Ft LED Ghost Happy Halloween Sign",
      price: "$34.99",
      why: "Retro ghost greeting sign with warm golden border glow that looks authentic mounted to a salvaged wooden door.",
      keyDetails: [
        "Vintage storybook ghost expression",
        "Warm golden LED perimeter backlighting",
        "Traditional Happy Halloween greeting banner",
        "Hangs cleanly on salvaged doors or gates",
      ],
      consider: "Warm golden glow beats cold white LEDs.",
      amazonUrl: "https://amzn.to/4hZl5JC",
      bestFor: "Salvaged door displays",
      badge: "Best Door Greeting",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-polka-dot-pumpkin",
      name: "Haunted Hill Farm 2.4-Ft. Polka Dot Checkered Pumpkin Stack Halloween Decor",
      image: polkaDotPumpkinImg,
      imageAlt: "Haunted Hill Farm 2.4-Ft Polka Dot Checkered Pumpkin Stack",
      price: "$49.99",
      why: "Checkered and polka dot courtly patterns that add high-end tailored contrast to weathered wooden crates.",
      keyDetails: [
        "Checkered and polka dot courtly patterns",
        "Sophisticated black, white, and gold accents",
        "2.4-foot graduated stacked silhouette",
        "Looks like vintage designer pottery",
      ],
      consider: "Adds tailored pattern interest to rustic crates.",
      amazonUrl: "https://amzn.to/3V2VMg6",
      bestFor: "Tiered crate risers",
      badge: "Best Patterned Stack",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-metal-scarecrow",
      name: "Haunted Hill Farm 3-Ft. LED Metal Scarecrow Halloween Decoration",
      image: metalScarecrowImg,
      imageAlt: "Haunted Hill Farm 3-Ft LED Metal Scarecrow",
      price: "$39.99",
      why: "Heavy-duty laser-cut steel scarecrow that sits beautifully anchored inside antique galvanized wash tubs.",
      keyDetails: [
        "Heavy-duty laser-cut steel construction",
        "Integrated warm white LED illumination",
        "Classic harvest scarecrow motif",
        "Weather-resistant powder-coated bronze finish",
      ],
      consider: "Anchors securely inside galvanized buckets.",
      amazonUrl: "https://amzn.to/4zOJic3",
      bestFor: "Galvanized tub planters",
      badge: "Best Metal Scarecrow",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-candle-blow-mold",
      name: "Haunted Hill Farm 3.3-Ft. Warm White LED Candle Halloween Blow Mold",
      image: candleBlowMoldImg,
      imageAlt: "Haunted Hill Farm 3.3-Ft Warm White LED Candle Blow Mold",
      price: "$59.99",
      why: "Classic blow mold candle with warm internal amber glow that creates an eerie display peeking from an open vintage suitcase.",
      keyDetails: [
        "Authentic hollow blow mold construction",
        "Warm internal amber LED lighting",
        "Substantial 3.3-foot vertical height",
        "100% weatherproof against rain and frost",
      ],
      consider: "Nestle inside open vintage luggage.",
      amazonUrl: "https://amzn.to/4wZhAH2",
      bestFor: "Vintage suitcase vignettes",
      badge: "Best Blow Mold",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-led-skeleton",
      name: "Haunted Hill Farm 2.3-Ft. White LED Skeleton Halloween Decoration",
      image: ledSkeletonImg,
      imageAlt: "Haunted Hill Farm 2.3-Ft White LED Skeleton",
      price: "$34.99",
      why: "Detailed skeletal sculpt with internal illumination that creates chilling reflection effects against antique mirrors.",
      keyDetails: [
        "Crisp white skeletal anatomy sculpt",
        "2.3-foot substantial size",
        "High contrast visibility against dark surfaces",
        "Internal LED glow illuminates ribs at night",
      ],
      consider: "Reflects hauntingly in clouded antique mirrors.",
      amazonUrl: "https://amzn.to/4gu19xh",
      bestFor: "Distressed mirror reflections",
      badge: "Best Reflection Prop",
      rating: 4.7,
    },
    {
      id: "haunted-hill-farm-summerween-pumpkin",
      name: "Haunted Hill Farm 2.4-Ft. Summerween Pumpkin Stack Halloween Decor",
      image: summerweenPumpkinImg,
      imageAlt: "Haunted Hill Farm 2.4-Ft Summerween Pumpkin Stack",
      price: "$46.99",
      why: "Pastel-toned pumpkin stack that looks charmingly arranged inside antique wooden garden carts and wheelbarrows.",
      keyDetails: [
        "Fresh pastel color palette reminiscent of 1950s decor",
        "Stacked graduated pumpkin forms",
        "Weatherproof lightweight resin build",
        "Stands out from standard orange and black decor",
      ],
      consider: "Arrange inside antique garden carts.",
      amazonUrl: "https://amzn.to/4i4l8nA",
      bestFor: "Antique garden carts",
      badge: "Best Cart Accent",
      rating: 4.7,
    },
    {
      id: "haunted-hill-farm-creepy-doll",
      name: "Haunted Hill Farm 2.9-Ft. Creepy Doll Halloween Animatronic",
      image: creepyDollImg,
      imageAlt: "Haunted Hill Farm 2.9-Ft Creepy Doll Animatronic",
      price: "$89.99",
      why: "Victorian porcelain-faced doll with motorized head turning that looks chillingly suspended inside antique wire birdcages.",
      keyDetails: [
        "Cracked porcelain antique doll sculpt",
        "Motorized head-turning and arm movement",
        "Vintage distressed Victorian dress",
        "Tinkling music box sound effects",
      ],
      consider: "Suspend inside hanging wire birdcages.",
      amazonUrl: "https://amzn.to/4h24WlD",
      bestFor: "Antique birdcage displays",
      badge: "Most Unsettling Prop",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-haunted-house-set",
      name: "Haunted Hill Farm LED Spooky Haunted House Set 3 pc.",
      image: hauntedHouseSetImg,
      imageAlt: "Haunted Hill Farm LED Spooky Haunted House Set 3 pc",
      price: "$69.99",
      why: "Trio of illuminated Victorian mansions that creates an architectural village scene on rustic paint can risers.",
      keyDetails: [
        "Set of 3 distinct Victorian manor silhouettes",
        "Warm LED backlighting through window panes",
        "Freestanding bases for steps or benches",
        "Creates a charming miniature illuminated village",
      ],
      consider: "Group on vintage industrial risers.",
      amazonUrl: "https://amzn.to/46yvbtS",
      bestFor: "Industrial can pedestals",
      badge: "Best Village Set",
      rating: 4.8,
    },
    {
      id: "haunted-hill-farm-bear-rocking-horse",
      name: "Haunted Hill Farm 2.1-Ft. Bear Riding Rocking Horse Halloween Animatronic",
      image: bearRockingHorseImg,
      imageAlt: "Haunted Hill Farm 2.1-Ft Bear Riding Rocking Horse Animatronic",
      price: "$79.99",
      why: "Motorized teddy bear on rocking horse that looks authentically discovered alongside vintage farm tools.",
      keyDetails: [
        "Detailed teddy bear and wooden rocking horse sculpt",
        "Continuous motorized rocking motion",
        "Nostalgic distressed toy aesthetic",
        "Charming nursery music box audio",
      ],
      consider: "Stage beside antique rakes and scythes.",
      amazonUrl: "https://amzn.to/4ybKvs7",
      bestFor: "Old farm tool scenes",
      badge: "Best Antique Toy",
      rating: 4.8,
    },
  ],

  faqs: [
    {
      q: "What's the best vintage item to start with for Halloween decorating?",
      a: "A weathered wooden ladder, antique fruit crate, or salvaged multi-pane window sash are the easiest and most versatile items. They instantly add vertical height, authentic patina, and rustic charm to porch steps.",
    },
    {
      q: "Where can I find vintage items for repurposing?",
      a: "Thrift stores, flea markets, architectural salvage yards, and garage sales are treasure troves. You can also explore your own attic, shed, or garage for forgotten tools, ladders, and jars.",
    },
    {
      q: "Can I mix modern weather-resistant props with real antiques?",
      a: "Yes! In fact, that is the secret to a long-lasting outdoor display. Pairing delicate antique wood with heavy-duty modern resin and LED props ensures your setup survives autumn rain and wind.",
    },
    {
      q: "How do I protect salvaged wood outdoors during fall?",
      a: "Coat raw wood with a clear matte water-repellent sealant before setting it outside. Keep vintage textiles and papers under covered porches to avoid water damage.",
    },
    {
      q: "Can I use real candles with repurposed vintage displays?",
      a: "Always use battery-operated flameless LED candles or UL-listed outdoor electric blow molds. Dry hay, vintage books, and weathered timber present serious fire hazards with real flames.",
    },
    {
      q: "What's the most versatile vintage container for Halloween?",
      a: "Vintage wooden apple crates and galvanized metal sap buckets are the most versatile — they function as sturdy pedestals, cubby displays, and weatherproof planters for scarecrows and pumpkin stacks.",
    },
  ],
};

export default article;
